name = "furni-platform-backend"
main = "src/index.ts"
compatibility_date = "2026-03-15"

[vars]
AUTH_PROVIDERS = "local,line,google"
LOCAL_AUTH_MODE = "form"

[[d1_databases]]
binding = "DB"
database_name = "furni-platform"
database_id = "26bda7d1-6dbc-43e1-9934-e8decfc2cfc7"

[assets]
directory = "./public"
binding = "ASSETS"

[observability.logs]
enabled = true

[env.preview]
name = "furni-platform-backend-preview"

[env.preview.vars]
AUTH_PROVIDERS = "local"
LOCAL_AUTH_MODE = "fixed_admin"
PREVIEW_ADMIN_DISPLAY_NAME = "Preview Admin"
PREVIEW_ADMIN_EMAIL = "preview-admin@davidfield.com.tw"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "furni-platform"
database_id = "26bda7d1-6dbc-43e1-9934-e8decfc2cfc7"

[[env.preview.routes]]
pattern = "preview-shop.davidfield.com.tw"
custom_domain = true

[env.production]
name = "furni-platform-backend-production"

[env.production.vars]
AUTH_PROVIDERS = "line,google"
LOCAL_AUTH_MODE = "disabled"
LINE_CLIENT_ID = "2009445563"
LINE_REDIRECT_URI = "https://shop.davidfield.com.tw/api/v1/auth/line/callback"
GOOGLE_CLIENT_ID = "7560189269-6rpm5f0ip5jvijiljkopdjsfnqauc2mi.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://shop.davidfield.com.tw/api/v1/auth/google/callback"

[[env.production.d1_databases]]
binding = "DB"
database_name = "furni-platform"
database_id = "26bda7d1-6dbc-43e1-9934-e8decfc2cfc7"

[[env.production.routes]]
pattern = "shop.davidfield.com.tw"
custom_domain = true
