from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path


TABLE_ORDER = [
    "users",
    "oauth_identities",
    "stores",
    "store_memberships",
    "categories",
    "products",
    "product_variants",
    "product_images",
    "product_categories",
    "collections",
    "collection_items",
    "collection_images",
    "collection_comments",
    "wishlists",
    "wishlist_items",
    "viewlists",
    "viewlist_items",
    "feed_slots",
    "highlight_products",
    "auth_sessions",
]

DELETE_ORDER = [
    "auth_sessions",
    "highlight_products",
    "feed_slots",
    "viewlist_items",
    "viewlists",
    "wishlist_items",
    "wishlists",
    "collection_comments",
    "collection_images",
    "collection_items",
    "collections",
    "product_categories",
    "product_images",
    "product_variants",
    "products",
    "categories",
    "store_memberships",
    "stores",
    "oauth_identities",
    "users",
]


def quote(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def export_table(conn: sqlite3.Connection, table_name: str) -> list[str]:
    columns = [row[1] for row in conn.execute(f"PRAGMA table_info({table_name})")]
    if not columns:
        return []

    rows = conn.execute(f"SELECT * FROM {table_name}").fetchall()
    if not rows:
        return []

    column_sql = ", ".join(columns)
    statements: list[str] = []
    for row in rows:
        values_sql = ", ".join(quote(value) for value in row)
        statements.append(
            f"INSERT INTO {table_name} ({column_sql}) VALUES ({values_sql});"
        )
    return statements


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export SQLite data as D1-compatible INSERT statements."
    )
    parser.add_argument(
        "--sqlite",
        default="furni.db",
        help="Path to the source SQLite database.",
    )
    parser.add_argument(
        "--output",
        default="deploy/cloudflare/seed.sql",
        help="Path to the generated SQL file.",
    )
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(sqlite_path) as conn:
        lines = [
            "-- Generated by scripts/export_sqlite_to_d1.py",
        ]

        for table_name in DELETE_ORDER:
            lines.append(f"DELETE FROM {table_name};")

        for table_name in TABLE_ORDER:
            lines.extend(export_table(conn, table_name))

        lines.extend(
            [
                "",
            ]
        )

    output_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
